# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Contextd < Formula
  desc "AI context and reasoning engine for Claude Code"
  homepage "https://github.com/fyrsmithlabs/contextd"
  version "0.1.0-alpha"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fyrsmithlabs/contextd/releases/download/v0.1.0-alpha/contextd_0.1.0-alpha_darwin_amd64.tar.gz"
      sha256 "491ca160f9b226028241648439b5e8b40f9d6f50de80c3e448159ac38362ee89"

      def install
        bin.install "contextd"
        bin.install "ctxd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fyrsmithlabs/contextd/releases/download/v0.1.0-alpha/contextd_0.1.0-alpha_darwin_arm64.tar.gz"
      sha256 "8196728b7b3f3603a5bf0d3d40fca866393a8bac78050bb42d567ab11c1e38ed"

      def install
        bin.install "contextd"
        bin.install "ctxd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fyrsmithlabs/contextd/releases/download/v0.1.0-alpha/contextd_0.1.0-alpha_linux_amd64.tar.gz"
      sha256 "0edd5fd1ae6bad6ea9593f2cc946ffb9e85558a78ec2c4dbbe9bf4c090c20c67"
      def install
        bin.install "contextd"
        bin.install "ctxd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fyrsmithlabs/contextd/releases/download/v0.1.0-alpha/contextd_0.1.0-alpha_linux_arm64.tar.gz"
      sha256 "71e4e71cabc308897f07dcf9aa0690a941c02d280a1284604e225606566759f1"
      def install
        bin.install "contextd"
        bin.install "ctxd"
      end
    end
  end

  test do
    system "#{bin}/contextd", "--help"
    system "#{bin}/ctxd", "--help"
  end
end
