# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Contextd < Formula
  desc "AI context and reasoning engine for Claude Code"
  homepage "https://github.com/fyrsmithlabs/contextd"
  version "0.1.0-alpha"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fyrsmithlabs/contextd/releases/download/v0.1.0-alpha/contextd_0.1.0-alpha_darwin_amd64.tar.gz"
      sha256 "747c697ca6f88fdad9d2c183604d54eeb50866d705c74d07e13fac8048dbf094"

      def install
        bin.install "contextd"
        bin.install "ctxd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fyrsmithlabs/contextd/releases/download/v0.1.0-alpha/contextd_0.1.0-alpha_darwin_arm64.tar.gz"
      sha256 "ac1ff8c7461f630dd7a247add0729aa4afebb7164d709024f0c474c97f5fe73d"

      def install
        bin.install "contextd"
        bin.install "ctxd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fyrsmithlabs/contextd/releases/download/v0.1.0-alpha/contextd_0.1.0-alpha_linux_amd64.tar.gz"
      sha256 "979b10999ee4dcca15e1fac424c866bb5b5639370434e1f8933f2f040a67c571"
      def install
        bin.install "contextd"
        bin.install "ctxd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fyrsmithlabs/contextd/releases/download/v0.1.0-alpha/contextd_0.1.0-alpha_linux_arm64.tar.gz"
      sha256 "0bff0ec913bafc7b5b84b62be158402ab24b1fa3b7081286271aa072e5b716a5"
      def install
        bin.install "contextd"
        bin.install "ctxd"
      end
    end
  end

  test do
    system "#{bin}/contextd", "--help"
    system "#{bin}/ctxd", "--help"
  end
end
