# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Contextd < Formula
  desc "AI context and reasoning engine for Claude Code"
  homepage "https://github.com/fyrsmithlabs/contextd"
  version "0.1.5"
  license "MIT"

  depends_on "onnxruntime"
  depends_on "qdrant"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fyrsmithlabs/contextd/releases/download/v0.1.5/contextd_0.1.5_darwin_amd64.tar.gz"
      sha256 "6d161b5aa610d4b0aa1fd5b3a3a4f282443178af6d4f65ed273753dca46667c6"

      def install
        bin.install "contextd"
        bin.install "ctxd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fyrsmithlabs/contextd/releases/download/v0.1.5/contextd_0.1.5_darwin_arm64.tar.gz"
      sha256 "278e51d7233ca4e360b2fc315fd1c5dddcc4c77e5fc9c924798a042af9c15660"

      def install
        bin.install "contextd"
        bin.install "ctxd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fyrsmithlabs/contextd/releases/download/v0.1.5/contextd_0.1.5_linux_amd64.tar.gz"
      sha256 "f313adb74235848b1259c0843038e0e2a5b217f42fe4063f92e4f20e166ac915"
      def install
        bin.install "contextd"
        bin.install "ctxd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fyrsmithlabs/contextd/releases/download/v0.1.5/contextd_0.1.5_linux_arm64.tar.gz"
      sha256 "a1416e4083b6665ad25b2f6501d3c4a6761199dc1491b73cda7afbbf690fe14a"
      def install
        bin.install "contextd"
        bin.install "ctxd"
      end
    end
  end

  service do
    run [opt_bin/"qdrant", "--uri", "0.0.0.0:6334"]
    keep_alive true
    working_dir HOMEBREW_PREFIX
    environment_variables:
      QDRANT__STORAGE__STORAGE_PATH: "#{var}/qdrant/storage"
  end

  test do
    system "#{bin}/contextd", "--help"
    system "#{bin}/ctxd", "--help"
  end
end
